spring:
  application:
    name: data-preload
  data:
    redis:
      host: localhost
      port: 6379
      password: admin
  logging:
    level:
      com.redis.om.spring: DEBUG
      io.lettuce.core.protocol: DEBUG
